# Generated by Django 4.1 on 2022-08-13 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comidas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Banquete',
        ),
        migrations.AlterModelOptions(
            name='banquete',
            options={'ordering': ['-create'], 'verbose_name': 'Banquete', 'verbose_name_plural': 'Banquetes'},
        ),
    ]
